### ISSUE TITLE
Needs Typescript support

### ISSUE THREAD

**Issue by ggedde** [dhershman1/vue-debounce#13]
This looks like a very simple and easy to use plugin, but I am using Typescript and getting errors as there is no Types enabled for vue-debounce.

If it will take too long to add could you maybe advise on how to declare a declaration for vue-debounce.

Thanks

**Comment by ggedde** [comment]
PS here is the error I am getting:
```
Could not find a declaration file for module 'vue-debounce'. '.../node_modules/vue-debounce/dist/vue-debounce.min.js' implicitly has an 'any' type.
  Try `npm install @types/vue-debounce` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-debounce';`
```

**Comment by dhershman1** [comment]
Hello @ggedde ! Thanks for using my little plugin! I don't use typescript much at all, I've written index.d files for my other libs but I'm not quite sure how I would do something similar for this one.

I know it's possible I will just have to look into how to accomplish this, it may be faster if you want to open a PR to create a `index.d.ts` file in the meantime. (I am going to talk to my buddy who uses typescript so that might take time)

**Comment by ggedde** [comment]
Thanks @dhershman1 
Unfortunately, I don't know how to create one either.
I have looked at others and tried to discuss it on discord with the vue typescript community, but no luck so far.

**Comment by dhershman1** [comment]
Thanks, like I said I've done it before but this one is a little different than those other tools. I know my friend is gonna take a look at it for me however.

**Comment by dhershman1** [comment]
#14 opened after switching which branch the PR is directed at it should be good to go.

**Comment by ggedde** [comment]
Thanks, New update working great!
