### ISSUE TITLE
Support params in function

### ISSUE THREAD

**Issue by VisualMafia** [dhershman1/vue-debounce#19]
Will there be support for parameters in the function? 

Case:
v-debounce="myFunc('param')"
after mounted component run myFunc three times. If change input function run five times five times etc...

**Comment by dhershman1** [comment]
You should be able to use a curried method to set params.

See issue #1 for more info.

**Comment by VisualMafia** [comment]
Thanks, I saw. But is implementation planned in a standard form, as I described above?

**Comment by dhershman1** [comment]
As of this moment no. It may be a functionality in the future, I would have to naturally curry the function but then that would require you to call your function even without params. So it is a little bit picky in how it would work.

But if it's needed enough then I can look into it sooner rather than later.

**Comment by VisualMafia** [comment]
Ok, thanks
