### ISSUE TITLE
Listening for multiple events

### ISSUE THREAD

**Issue by adamreisnz** [dhershman1/vue-debounce#2]
Hello, is it possible with this module to listen for multiple events?
For example I want to keep listening to the onkeyup event for most cases, but for our search field it would be good to also trigger on the search event.

The config parameter only seems to allow you to specify one event though. Thoughts?

**Comment by dhershman1** [comment]
Hmm, I can probably do something like this through modifiers similar to how .lock and .unlock work. That way you can specify an overwrite to the default key.

I believe I can do that on the fly if I remember right, I'll have to take a look

**Comment by dhershman1** [comment]
Finally got some free time to check into this:

Sadly with the way Vue binds directives I would be unable to accomplish this per input as it would be impossible (and slow) to account for every possible outcome. I can however make it so that the `listenTo` option can take an array of events to listen to. However this means it's applied to all of the inputs using `v-debounce`.

With that drawback I am unsure if this would still be helpful or not to implement. Thoughts?

**Comment by adamreisnz** [comment]
Hmm, what exactly is the limitation that prevents it from being applied to a single input?

If the only drawback with the other approach is that it will be applied to all inputs, I still think that's worthwhile implementing. If the event is passed to the handler, we can always filter out unwanted event triggers if necessary, but at least it will allow us to apply it to multiple events when we do need that.

Thanks for looking into it.

**Comment by dhershman1** [comment]
The main drawback for making it say a modifier is that I can't really guess what the event is, since the modifiers are given to my module as an object. I'd have to somehow know which one you are using. I could have you list all the events you _might_ use, but then I'd need to loop through everytime to figure out which one it is to set a handler function for it.

**Comment by adamreisnz** [comment]
I see what you mean. Would something like this be feasible to implement?

```html
<input v-debounce:300="myFunc" v-debounce-listen-to="onkeyup,onsearch,oninput" type="text" />
```

**Comment by dhershman1** [comment]
Hmm, that may be something to look into. I don't know if a new directive would solve the issue or not, depending on if my current one can use it or not.

I will build out some test scenarios and see what I can come up with.

**Comment by adamreisnz** [comment]
I may be naive and coming from an Angular background, normally a directive could read the value of any other attribute on the HTML element. So no need to create another directive, just read and use the value of another property. Of course if it's not provided it would default back to the defaults.

Let me know how you go!

**Comment by dhershman1** [comment]
I should have some kind of access to the elements props/attributes I just don't remember all of the items I get back within the call. Lol I will look tomorrow digging through docs isn't very fun on mobile.

**Comment by dhershman1** [comment]
PR created to implement some of this functionality #3 if you wanted to take a look

**Comment by dhershman1** [comment]
Release merged, published, and sent to NPM.

**Comment by adamreisnz** [comment]
Great, I'll take it for a spin soon :) Thanks 👍
