### ISSUE TITLE
How can I use vue-debounce with v-model?

### ISSUE THREAD

**Issue by ZerdoX-x** [dhershman1/vue-debounce#27]
I want to debounce v-model, can vue-debounce help me?

**Comment by dhershman1** [comment]
tl;dr: I don't think there is a good way to use vue-debounce in order to debounce a v-model.

Theoretically yes,

```vue
<template>
  <input v-model="test" v-debounce="foobar" />
</template>
<script>
export default {
  data () {
    return {
      test: ''
    }
  },

  methods: {
    foobar (val) {
      this.test = val
    }
  }
}
</script>
```

However, the implications of this I am unsure, you may not see any changes in the input until the debounce updates the v-model, so on and so fourth.

You may however be able to use the debounce function directly in this case, though I am unsure of how at this time...

**Comment by ZerdoX-x** [comment]
Thank you!
