### ISSUE TITLE
Using class method breaks inheritance

### ISSUE THREAD

**Issue by ggedde** [dhershman1/vue-debounce#28]
When using v-debounce="myClass.action"
I get an error that within my class that "this" is undefined.

Here is an example of my class: 
```
class myClass {
	data = {
		name: 'Testing'
	};

	constructor() {
		console.log(this.data);
	}

	public action() {
		console.log(this.data);
	}
}
```

When the class initializes I get the console log of "{name: Testing}"

But when I Type into my field I get the following response:
`Uncaught TypeError: Cannot read property 'data' of undefined`

So I am curious if v-debounce is overriding the Class inheritance or something. Or possibly I am not coding this correctly :)

Any help would be appreciated.
Thanks

**Comment by ggedde** [comment]
I was able to resolve by changing my class to a Static class, but that required a bunch of rework.  So it seems just instance based classes have conflicts with "this".

**Comment by dhershman1** [comment]
I want to say that vue debounce shouldn't be directly affecting your inheritance but I don't want to dismiss it either.

What the lib does is wraps the function you give me into a handler that is then used for event listeners. None of these are arrow functions so that may be where you lose your scope.

Do you mind sending me a full example of some code you ran into this problem with, as I don't use classes I am unsure of where this might be setup/used.

**Comment by dhershman1** [comment]
I'm hoping #31 may have addressed this issue, so I'm closing it for now feel free to re open if needed.

**Comment by ggedde** [comment]
Ok thanks. I will try and test it soon.
